#!/bin/bash

# https://github.com/figmentum/.tmux.conf.customization
#   This project is licensed under MIT license.
#   Copyright 2022- figmentum (https://siesta.pm)

# free_size/totoal_size of /
df -m | awk '$6 ~ /^\/$/ {printf(" %.1fG"), $4 / 1024}'
